# Generated by Django 3.0.8 on 2020-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200723_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='postit',
            name='noteText',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postit',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
