# Generated by Django 3.0.8 on 2020-07-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200723_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='noteText',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
