# Generated by Django 3.0.8 on 2020-07-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20200723_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='postit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
